export { getDriveConfig, getDriveConfigIssue } from './config'
export { describeDriveError, DriveError } from './errors'
export type { DriveErrorCode } from './errors'
export { fileIconKind, fileTypeLabel, mergeFiles } from './files'
export { connectDriveAccount, pickDriveFiles, shareFilesWithAnyone, shareFilesWithUser } from './operations'
export type { ShareFailure } from './operations'
export { preloadGoogleScripts } from './loadScripts'
export { disconnectDrive } from './auth'
export type { DriveAccount } from './api'
